---
abstract: 'access to is_utf8_string() Perl API function'
author:
  - 'Jozef Kutej <jkutej@cpan.org>'
build_requires:
  Encode: 0
  ExtUtils::CBuilder: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3601'
keywords:
  - utf-8
  - string
  - perlapi
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: String-isUTF8
provides:
  String::isUTF8:
    file: lib/String/isUTF8.pm
    version: 0.01
resources:
  bugtracker: http://github.com/jozef/String-isUTF8/issues
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jozef/String-isUTF8.git
version: 0.01
